server:
  port: 8080

spring:
# lettuce
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
#    password: redis123
    port: 6379
    jessionId: sessionId

  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/backend?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
#    url: jdbc:mysql://120.78.185.50:3306/backend?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/admin/
#    prefix: file:./templates/admin/
  mvc:
    static-path-pattern: /**
    favicon:
      enabled: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

authCode:
  tokenKey: src:sessionManage
  captchaKey: src:captcha
  expire:
    seconds: 60

filepath: /Users/chenghongzhi/GitHub/shirodemo/upload/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
