server:
  port: 8080

spring:
# lettuce
  redis:
    database: 0
    host: 120.78.185.50
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: redis123
    port: 6379

  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/backend?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
#    url: jdbc:mysql://120.78.185.50:3306/backend?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/admin/
#    prefix: file:./templates/admin/
  mvc:
    static-path-pattern: /**
    favicon:
      enabled: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
# 这里填写项目的绝对路径，用于文件上传的绝对地址，也是文件下载的地址
#  path: /javaweb/static/upload/
  path: /Users/chenghongzhi/GitHub/shirodemo/src/main/resources/static/upload/
# url:表示静态资源的访问目录 格式为域名/static/文件上传的文件夹的名称
#  url: localhost:8080/static/upload/
  url: 120.78.185.50:8080/static/upload/

#  rabbitmq:
#    host: 120.78.185.50
#    port: 5672
#    username: admin
#    password: admin123


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
